{% set name = "pyhough" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyhough-{{ version }}.tar.gz
  sha256: 0cf95bf0baa58eb238071375b1324fe15d924b1625987653e4bceae36b23c85c

build:
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - versioneer
  run:
    - python >={{ python_min }}
    - pyfstat
    - numpy
    - matplotlib-base
# not requiring tests of pip check because upstream package lalsuite prevents build
test:
  imports:
    - pyhough
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/andrew-l-miller/pyhough
  summary: Package to compute the Generalized Frequency-Hough Transform to search for continuous gravitational waves in LIGO, Virgo and KAGRA data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andrew-l-miller
